---
title: "Appendix D.4 Functions"
format: html
filters:
  - pyodide
---

Appendix D: A crash course in Python  
NUMA01: Computational Programming with Python  
Malin Christersson, Robert Klofkorn  

## D.4 Functions in Python

### How to define a function in Python

**Example D.47 (Defining functions in Python)**  
In the following code we define $f(x) = x^2 - 5x + 4$ in Python and compute $f(3)$.

```{pyodide-python}
#| read-only: false
def f(x):
    y = x**2 - 5 * x + 4
    return y

z = f(3)
print(z)
```

Explanation:

1. `def f(x):` tells Python that a function named `f` is being defined.
2. The `return` value is the output of the function.
3. When we write `f(3)`, the function code is run with `x = 3`.

### Exercise D.48

1. Use the if-control statement to implement the absolute value function. Use it on
   a few values to check that it works.
2. Implement the absolute value function without using the if-control statement.

Remark: It is not really necessary to program the absolute value function by hand
since it already exists in Python as `abs(x)`.

```{pyodide-python}
#| read-only: false
# TODO: implement absolute value with if.
```

```{pyodide-python}
#| read-only: false
# TODO: implement absolute value without if.
```

### Exercise D.49

Write the code for a function that will take a list of numbers as input and return
their product as output. This is analogous to the built-in function `sum()` which
returns the sum.

```{pyodide-python}
#| read-only: false
# TODO: implement a product function.
```

### Warning: the importance of local namespaces

Variables created inside a function are local and cannot be accessed outside the
function. This is a common source of bugs.

**Example D.50**  
The following code makes no sense and will crash.

```{pyodide-python}
#| read-only: false
x = 3

def f(x):
    y = x**2 - 5 * x + 4
    return y

print(y)
```

**Example D.51**  
The following code also crashes.

```{pyodide-python}
#| read-only: false
x = 3

def f(x):
    y = x**2 - 5 * x + 4
    return y

f(x)
print(y)
```

The variable `y` only exists inside the function definition. After the function
returns, local variables are deleted.

**Example D.52**  
Thanks to local namespaces, we can be sure that the following code works:

```{pyodide-python}
#| read-only: false
a = [1, 2, 3]
b = [4, 5, 6]
c = sum(a)
print(b)
```

### How to plot functions in Python using lists

**Example D.53 (Plotting with datatype list)**  
The following code plots $f(x) = x^2 + 2x + 3$ over the interval $[0, 1]$.

```{pyodide-python}
#| read-only: false
import matplotlib.pyplot as plt

def f(x):
    y = x**2 + 2 * x + 3
    return y

X = [n / 10 for n in range(0, 11)]
Y = [f(x) for x in X]

plt.plot(X, Y)
plt.show()
```

The command `plt.plot(X, Y)` connects the points with straight line segments. If you
use `plt.plot(X, Y, "bo")` you will get blue dots instead of a line.

### Exercise D.54

Plot the functions you implemented in Exercise D.48 on $[1/2, 2]$.

```{pyodide-python}
#| read-only: false
# TODO: plot your absolute value functions on [1/2, 2].
```

### Exercise D.55

Consider the following code:

```{pyodide-python}
#| read-only: false
import matplotlib.pyplot as plt

N = 10**4

def a(k):
    return 1 / 2**k

def S(a_func, n):
    return sum([a_func(k) for k in range(0, n)])

n_values = [n for n in range(0, N)]
Y = [S(a, n) for n in n_values]

plt.plot(n_values, Y, "bo")
```

1. Explain in mathematical terms what this code does.
2. The symbol `a` takes more than one role in the above code. Explain what roles
   these are.
3. Make the code easier to read by giving `a` different names where possible.

### Plotting functions using numpy arrays

Numpy arrays are like lists, but restricted to numeric entries. This makes it possible
to do fast, element-wise operations.

**Example D.56 (Features of numpy arrays)**

```{pyodide-python}
#| read-only: false
import numpy as np

def f(x):
    return x**2

a = [1, 2, 3, 4]
b = [1, 2, 5, 3]

A = np.array(a)
B = np.array(b)

C = A - B
D = A + B
E = A / B

F = np.zeros(3)
G = np.ones(4)
H = np.arange(4)
I = np.linspace(0, 1, 5)

J = I.tolist()
K = f(A)

print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)
print("E =", E)
print("F =", F)
print("G =", G)
print("H =", H)
print("I =", I)
print("J =", J)
print("K =", K)
```

Notes:

- `np.linspace(a, b, N)` creates `N` equally spaced points in `[a, b]`.
- Applying a function to an array is done element-wise.

**Example D.57**  
The following code gives exactly the same output as Example D.53.

```{pyodide-python}
#| read-only: false
import matplotlib.pyplot as plt
import numpy as np

def f(x):
    y = x**2 + 2 * x + 3
    return y

X = np.linspace(0, 1, 11)
Y = f(X)

plt.plot(X, Y)
plt.show()
```

### Exercise D.58

Try to use numpy arrays to plot the functions from Exercise D.48. For one of them,
the code will not work. Can you imagine why?

### Predefined functions in Python

**Remark D.59 (Built-in functions in Python)**  
Here is a list of some functions that are built into Python:

- `abs(x)` computes the absolute value of `x`.
- `complex(a, b)` returns the complex number `a + ib`.
- `float(x)` converts an integer to a float.
- `int(x)` converts a float to an integer (rounds down).
- `round(a, n)` rounds the floating point number `a` to `n` digits.
- `type(x)` returns the datatype of the variable `x`.

For a full list, see <https://docs.python.org/3/library/functions.html>.

**Remark D.60 (Functions in the numpy package)**  
To use these functions, start your code with `import numpy as np`.

- `np.exp(x)` exponential function
- `np.log(x)` natural log
- `np.log2(x)` log base 2
- `np.log10(x)` log base 10
- `np.sin(x)` sine (radians)
- `np.cos(x)` cosine (radians)
- `np.tan(x)` tangent (radians)
- `np.arcsin(x)` arcsine
- `np.arccos(x)` arccosine
- `np.arctan(x)` arctangent
- `np.absolute(x)` absolute value
- `np.deg2rad(x)` degrees to radians
- `np.rad2deg(x)` radians to degrees
- `np.sum(x)` sum of elements
- `np.prod(x)` product of elements
- `np.imag(z)` imaginary part
- `np.real(z)` real part
- `np.angle(z)` angle of a complex number (radians)
- `np.conj(z)` complex conjugate

Some constants:

- `np.pi`
- `np.e`

More info: <https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html>

**Example D.61**

```{pyodide-python}
#| read-only: false
import numpy as np

y = np.sin(np.pi)
print(y)
```

There are other packages with even more functions, such as `math` and `scipy`. In
particular, `numpy` makes the `math` package mostly obsolete when working with
numpy arrays.
